version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.4
    working_directory: ~/go/src/test
    steps:
      - checkout
      - run:
          name: Env Setup
          command: echo 'export PATH=/go/bin/:${PATH}' >> $BASH_ENV
      - run:
          name: base64 decode firebase file
          # ファイルに改行が含まれているので`-i`オプションを付ける
          command: echo $FIREBASE_TOKEN | base64 -di > firebase-auth.json
      - run:
          name: Go get library
          command: go get -t -v -d ./...
      - run:
          name: Go Auto Test
          command: GO_ENV=production go test -cover -v
